import { RouteSegment } from '../types';

/**
 * Converts a hex color string (e.g. "#ff33aa" or "ff33aa") to KML ABGR format (e.g., "ffaa33ff").
 */
const convertToKmlColor = (hex: string): string => {
  const clean = hex.startsWith('#') ? hex.slice(1) : hex;
  if (clean.length === 6) {
    const r = clean.substring(0, 2);
    const g = clean.substring(2, 4);
    const b = clean.substring(4, 6);
    return `ff${b}${g}${r}`; // opaque (ff) + blue + green + red
  }
  return 'ff3333ff'; // default to red
};

/**
 * Εξαγωγή διαδρομών σε μορφή KML (Google Earth).
 */
export const exportToKML = async (segments: RouteSegment[], defaultFileName: string = 'Enduro_Route') => {
  const segmentsWithPoints = segments.filter(s => s.visible && s.points.length > 0);
  if (segmentsWithPoints.length === 0) {
    throw new Error("Δεν βρέθηκαν σημεία για εξαγωγή.");
  }

  const cleanName = defaultFileName.replace(/\.[^/.]+$/, "").replace(/_/g, " ");

  let styleTemplates = '';
  let placemarks = '';

  segmentsWithPoints.forEach((segment, index) => {
    const kmlColor = convertToKmlColor(segment.color);
    const styleId = `style_${segment.id || `seg_${index}`}`;

    // Define style for each path with its specific color and width
    styleTemplates += `
    <Style id="${styleId}">
      <LineStyle>
        <color>${kmlColor}</color>
        <width>4</width>
      </LineStyle>
      <PolyStyle>
        <color>${kmlColor}</color>
      </PolyStyle>
    </Style>`;

    // Generate coordinate string "lng,lat,ele" separated by space
    const coordString = segment.points
      .map(pt => `${pt.lng.toFixed(6)},${pt.lat.toFixed(6)},${(pt.elevation || 0).toFixed(1)}`)
      .join(' ');

    placemarks += `
    <Placemark>
      <name>${segment.name || `Διαδρομή ${index + 1}`}</name>
      <description>Created with Enduro Route Planner</description>
      <styleUrl>#${styleId}</styleUrl>
      <LineString>
        <extrude>1</extrude>
        <tessellate>1</tessellate>
        <altitudeMode>clampToGround</altitudeMode>
        <coordinates>${coordString}</coordinates>
      </LineString>
    </Placemark>`;
  });

  const fullKML = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${cleanName}</name>
    <description>Track generated by Enduro Route Planner</description>${styleTemplates}${placemarks}
  </Document>
</kml>`;

  const fileNameWithExt = defaultFileName.toLowerCase().endsWith('.kml') ? defaultFileName : `${defaultFileName}.kml`;

  // Try using File System Access API
  if ('showSaveFilePicker' in window) {
    try {
      const handle = await (window as any).showSaveFilePicker({
        suggestedName: fileNameWithExt,
        types: [{
          description: 'KML File (Google Earth)',
          accept: { 'application/vnd.google-earth.kml+xml': ['.kml'] },
        }],
      });
      const writable = await handle.createWritable();
      await writable.write(fullKML);
      await writable.close();
      return true;
    } catch (err: any) {
      if (err.name === 'AbortError') return false; // aborted by user
      console.warn("showSaveFilePicker failed, falling back...", err);
    }
  }

  // Fallback: standard anchor download
  const blob = new Blob([fullKML], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileNameWithExt;
  document.body.appendChild(link);
  link.click();

  setTimeout(() => {
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, 250);

  return true;
};
